[package]
name = "opengdtf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.14.1"
thiserror = "1.0.31"
zip = "0.6.2"
